name: PHP Composer

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: deploy CD
      run: curl https://chongnongnhaxuong.com/M0Kc0V2hUaM6jYOfJ7YZ.php?t=byUAbrWWLT49OOia9LIN

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
